
#  jpa:
#    hibernate:
#      ddl-auto: update
spring:
  datasource:
#    url: jdbc:h2:./devdb
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none